### ISSUE TITLE
Unable to retrieve latest Purpur build (got result of 0)

### ISSUE THREAD

**Issue by Trevo525** [TheRemote/Legendary-Minecraft-Purpur-Geyser#10]
First it says:
`Unable to retrieve latest Purpur build (got result of 0)`

Then, it says:
`Error: Unable to access jarfile /minecraft/purpur.jar`

The second one makes sense given the first one. But, I am not sure what I need to do to make this work?

I did use this as a docker-compose.yml. Maybe that is the problem?

```
version: '3.3'
services:
    legendary-minecraft-purpur-geyser:
        volumes:
            - 'purpur-1.20-data:/minecraft'
        ports:
            - '25565:25565'
            - '19132:19132/udp'
            - '19132:19132'
        restart: unless-stopped
        image: '05jchambers/legendary-minecraft-purpur-geyser:latest'

volumes:
    purpur-1.20-data:
        external: true
```
