### ISSUE TITLE
NoBackup doesn't seem to work

### ISSUE THREAD

**Issue by miniksa** [TheRemote/Legendary-Minecraft-Purpur-Geyser#13]
I'm using Docker compose and I've specified:

```
services:
  minecraft:
    image: 05jchambers/legendary-minecraft-purpur-geyser:latest
    environment:
      - TZ=America/Los_Angeles
      - NoBackup="plugins/dynmap/web,plugins/dynmap"
      - NoPermCheck="Y"
 ```

But no matter what, the NoBackup doesn't seem to get parsed and applied correctly. This is very frustrating because the dynmap maps are HUGE and take forever to backup on startup.

I'm also kind of frustrated that there's no "SkipAllBackups='Y'" option here.

I'll look into perhaps sending a PR, but just reporting this in case you have an idea of how I'm doing it wrong.
